-- Atelier state. One SQLite file, no migrations framework: schema_version is
-- checked at open and the upgrade path is a switch in db/index.ts.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- A browser profile that has ever paired. Identity is generated by the
-- extension on install and stored in chrome.storage.local, so it survives a
-- restart but not a profile wipe.
CREATE TABLE IF NOT EXISTS profile (
  id            TEXT PRIMARY KEY,
  label         TEXT NOT NULL,
  browser       TEXT NOT NULL DEFAULT 'chrome',
  -- Chrome's --profile-directory value, resolved from Local State when we can,
  -- so the daemon can launch the right window instead of asking the human.
  profile_dir   TEXT,
  last_seen_at  TEXT
);

CREATE TABLE IF NOT EXISTS workflow (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'draft',
  origins     TEXT NOT NULL DEFAULT '[]',
  profile_id  TEXT REFERENCES profile(id),
  inputs      TEXT NOT NULL DEFAULT '[]',
  steps       TEXT NOT NULL DEFAULT '[]',
  produces    TEXT NOT NULL DEFAULT 'none',
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS job (
  id             TEXT PRIMARY KEY,
  workflow_id    TEXT NOT NULL REFERENCES workflow(id),
  inputs         TEXT NOT NULL DEFAULT '{}',
  status         TEXT NOT NULL DEFAULT 'queued',
  step_index     INTEGER NOT NULL DEFAULT 0,
  step_count     INTEGER NOT NULL DEFAULT 0,
  blocked_reason TEXT,
  error          TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS job_status_idx ON job(status);

-- Append-only. This is how a cold session reconstructs what a job actually did.
CREATE TABLE IF NOT EXISTS job_event (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id  TEXT NOT NULL REFERENCES job(id),
  at      TEXT NOT NULL,
  kind    TEXT NOT NULL,
  detail  TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS job_event_job_idx ON job_event(job_id, id);

CREATE TABLE IF NOT EXISTS asset (
  id            TEXT PRIMARY KEY,
  sha256        TEXT NOT NULL,
  mime          TEXT NOT NULL,
  bytes         INTEGER NOT NULL,
  width         INTEGER,
  height        INTEGER,
  job_id        TEXT REFERENCES job(id),
  workflow_name TEXT,
  prompt        TEXT,
  description   TEXT,
  tags          TEXT NOT NULL DEFAULT '[]',
  created_at    TEXT NOT NULL
);

-- Content-addressed storage means the same image generated twice is one file,
-- but it stays two assets with two prompts. The index is for dedup lookups.
CREATE INDEX IF NOT EXISTS asset_sha_idx ON asset(sha256);

-- Raw recordings, before the validation pass turns them into a workflow.
CREATE TABLE IF NOT EXISTS draft (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  profile_id  TEXT REFERENCES profile(id),
  origins     TEXT NOT NULL DEFAULT '[]',
  raw         TEXT NOT NULL,
  reviewed    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL
);

-- What each step actually matched on, last time it ran. Replay tries selector
-- candidates best-first and takes whichever resolves, which is what makes a
-- workflow survive a redeploy — and also what hides one, because a step quietly
-- matching on position looks identical to one matching on a data-testid. This
-- is the only record of the difference.
CREATE TABLE IF NOT EXISTS step_health (
  workflow_id TEXT NOT NULL REFERENCES workflow(id) ON DELETE CASCADE,
  step_id     TEXT NOT NULL,
  strategy    TEXT NOT NULL,
  score       INTEGER NOT NULL,
  at          TEXT NOT NULL,
  PRIMARY KEY (workflow_id, step_id)
);
