-- Atelier state. One SQLite file, no migrations framework: schema_version is
-- checked at open and the upgrade path is a switch in db/index.ts.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- A browser profile that has ever paired. Identity is generated by the
-- extension on install and stored in chrome.storage.local, so it survives a
-- restart but not a profile wipe.
CREATE TABLE IF NOT EXISTS profile (
  id            TEXT PRIMARY KEY,
  label         TEXT NOT NULL,
  browser       TEXT NOT NULL DEFAULT 'chrome',
  -- Chrome's --profile-directory value, resolved from Local State when we can,
  -- so the daemon can launch the right window instead of asking the human.
  profile_dir   TEXT,
  last_seen_at  TEXT
);

-- Everything Atelier owns belongs to exactly one project. One active project at
-- a time, held in meta.active_project, the way kubectl holds a current context.
CREATE TABLE IF NOT EXISTS project (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  slug       TEXT NOT NULL UNIQUE,
  note       TEXT,
  -- The bearer token an agent presents on /mcp. Per project rather than per
  -- daemon: the token is what says where a session is working, so handing one
  -- out is the whole of "connect this repo to this project" and nothing has to
  -- be chosen afterwards. Generated on creation; never blank.
  token      TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workflow (
  id          TEXT PRIMARY KEY,
  project_id  TEXT NOT NULL REFERENCES project(id),
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'draft',
  origins     TEXT NOT NULL DEFAULT '[]',
  profile_id  TEXT REFERENCES profile(id),
  inputs      TEXT NOT NULL DEFAULT '[]',
  steps       TEXT NOT NULL DEFAULT '[]',
  produces    TEXT NOT NULL DEFAULT 'none',
  -- How long to settle between steps. A second is the floor as well as the
  -- default: a page that needs none is not harmed by one, and a page that
  -- needs it gives no signal that anything could wait on.
  step_delay_ms INTEGER NOT NULL DEFAULT 1000,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL,
  -- Scoped per project rather than globally: "the export workflow" is a name
  -- you should be able to have once per client, not once ever.
  UNIQUE (project_id, name)
);

CREATE TABLE IF NOT EXISTS job (
  id             TEXT PRIMARY KEY,
  project_id     TEXT NOT NULL REFERENCES project(id),
  workflow_id    TEXT NOT NULL REFERENCES workflow(id),
  inputs         TEXT NOT NULL DEFAULT '{}',
  status         TEXT NOT NULL DEFAULT 'queued',
  step_index     INTEGER NOT NULL DEFAULT 0,
  step_count     INTEGER NOT NULL DEFAULT 0,
  blocked_reason TEXT,
  error          TEXT,
  -- A run started from the dashboard or the popup to check a workflow still
  -- works. It uses the values recorded with the workflow rather than a
  -- caller's, so it is worth telling apart in the history.
  is_test        INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS job_status_idx ON job(status);

-- Append-only. This is how a cold session reconstructs what a job actually did.
CREATE TABLE IF NOT EXISTS job_event (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id  TEXT NOT NULL REFERENCES job(id),
  at      TEXT NOT NULL,
  kind    TEXT NOT NULL,
  detail  TEXT NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS job_event_job_idx ON job_event(job_id, id);

CREATE TABLE IF NOT EXISTS asset (
  id            TEXT PRIMARY KEY,
  project_id    TEXT NOT NULL REFERENCES project(id),
  sha256        TEXT NOT NULL,
  mime          TEXT NOT NULL,
  bytes         INTEGER NOT NULL,
  width         INTEGER,
  height        INTEGER,
  job_id        TEXT REFERENCES job(id),
  workflow_name TEXT,
  prompt        TEXT,
  description   TEXT,
  tags          TEXT NOT NULL DEFAULT '[]',
  created_at    TEXT NOT NULL
);

-- Content-addressed storage means the same image generated twice is one file,
-- but it stays two assets with two prompts. The index is for dedup lookups.
CREATE INDEX IF NOT EXISTS asset_sha_idx ON asset(sha256);

-- Raw recordings, before the validation pass turns them into a workflow.
CREATE TABLE IF NOT EXISTS draft (
  id          TEXT PRIMARY KEY,
  project_id  TEXT NOT NULL REFERENCES project(id),
  name        TEXT NOT NULL,
  profile_id  TEXT REFERENCES profile(id),
  origins     TEXT NOT NULL DEFAULT '[]',
  raw         TEXT NOT NULL,
  reviewed    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL
);

-- What each step actually matched on, last time it ran. Replay tries selector
-- candidates best-first and takes whichever resolves, which is what makes a
-- workflow survive a redeploy — and also what hides one, because a step quietly
-- matching on position looks identical to one matching on a data-testid. This
-- is the only record of the difference.
CREATE TABLE IF NOT EXISTS step_health (
  workflow_id TEXT NOT NULL REFERENCES workflow(id) ON DELETE CASCADE,
  step_id     TEXT NOT NULL,
  strategy    TEXT NOT NULL,
  score       INTEGER NOT NULL,
  at          TEXT NOT NULL,
  PRIMARY KEY (workflow_id, step_id)
);

-- The project_id indexes are created in db/index.ts, after the migration has
-- added the columns. They cannot live here: this file runs first, and on an
-- existing database CREATE TABLE IF NOT EXISTS is a no-op, so indexing a column
-- the old table does not have yet fails the whole open.
