/**
 * The shared secret that makes a downloadable .mcp.json mean something.
 *
 * Until the MCP surface was served over HTTP, "only local processes can reach
 * the port" was the whole of the pairing. A config file you hand to an agent
 * needs something in it, and a container publishing a port needs a boundary
 * that does not depend on what the socket's remote address happens to look
 * like from inside a bridge network.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, readFileSync, statSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

process.env.ATELIER_HOME = mkdtempSync(join(tmpdir(), 'atelier-token-'))
delete process.env.ATELIER_TOKEN

const { readOrCreateToken, TOKEN_FILE } = await import('../src/core/token.ts')

test('a token is created on first use, so nothing has to be generated by hand', () => {
  assert.equal(existsSync(TOKEN_FILE), false)
  const token = readOrCreateToken()
  assert.ok(token.length >= 32, 'long enough not to be guessed')
  assert.equal(existsSync(TOKEN_FILE), true)
})

test('the same token comes back next time — a config file handed out stays valid', () => {
  assert.equal(readOrCreateToken(), readOrCreateToken())
  assert.equal(readOrCreateToken(), readFileSync(TOKEN_FILE, 'utf-8').trim())
})

test('the token file is readable only by its owner', () => {
  readOrCreateToken()
  // It is the credential for everything the daemon can do to a browser. Other
  // users on a shared machine are exactly who the file mode is for.
  assert.equal(statSync(TOKEN_FILE).mode & 0o077, 0, 'no group or other bits')
})

test('ATELIER_TOKEN wins, so a compose file can pin one instead of reading it back', () => {
  process.env.ATELIER_TOKEN = 'pinned-by-the-environment'
  assert.equal(readOrCreateToken(), 'pinned-by-the-environment')
  delete process.env.ATELIER_TOKEN
})

test('a blank ATELIER_TOKEN is ignored rather than accepted as an empty password', () => {
  process.env.ATELIER_TOKEN = '   '
  assert.notEqual(readOrCreateToken(), '')
  assert.equal(readOrCreateToken(), readFileSync(TOKEN_FILE, 'utf-8').trim())
  delete process.env.ATELIER_TOKEN
})
